/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.POSTransaction.view;

import com.POSGlobal.controller.clsGlobalVarClass;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

public class frmAgainstAdvBookorder extends javax.swing.JPanel 
{
     String selectquery,billDate;
     Date date;
     int year,month,day;
     String today;
     frmDirectBiller objDirectBiller;
     
    public frmAgainstAdvBookorder(Object Obj ) 
    {  
        initComponents();
        try
        {
            String bdte=clsGlobalVarClass.gPOSStartDate;
            SimpleDateFormat dFormat=new SimpleDateFormat("yyyy-MM-dd");
            Date bDate=dFormat.parse(bdte);
            String date1=(bDate.getYear()+1900)+"-"+(bDate.getMonth()+1)+"-"+bDate.getDate();
            String time=bDate.getHours()+":"+bDate.getMinutes()+":"+bDate.getSeconds();
            billDate=date1;
            date=new Date();
            year=date.getYear()+1900;
            month=date.getMonth()+1;
            day=date.getDate();
            today=year+"-"+month+"-"+day;   
            objDirectBiller=(frmDirectBiller)Obj;
            filltable();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public void filltable()
    {
        try
        {
            DefaultTableModel dm=new DefaultTableModel()
            {
                @Override
                public boolean isCellEditable(int row, int column)
                {
                    //all cells false
                    return false;
                }
            };
            dm.getDataVector().removeAllElements();
            dm.addColumn("AdvOrderNo.");   
            dm.addColumn("Mobile No.");
            dm.addColumn("CustName");
            dm.addColumn("Adv Amount");

            selectquery="Select a.strAdvBookingNo,c.longMobileNo,c.strCustomerName,b.dblAdvDeposite"
                    + " from tbladvbookbillhd  a, tbladvancereceipthd b, tblcustomermaster c "
                    + "Where a.strAdvBookingNo=b.strAdvBookingNo  "
                    + "and a.strCustomerCode = c.strCustomerCode "
                    + "and date(a.dteOrderFor)='"+today+"' "
                    + "and a.strAdvBookingNo NOT IN (select strAdvBookingNo from tblbillhd)";
            System.out.println(selectquery);
            ResultSet rsAdvOrderList=clsGlobalVarClass.dbMysql.executeResultSet(selectquery);           
            while(rsAdvOrderList.next())
            {
                Object[] rows={rsAdvOrderList.getString(1),rsAdvOrderList.getString(2),rsAdvOrderList.getString(3),rsAdvOrderList.getString(4)};
                dm.addRow(rows);
            }
            rsAdvOrderList.close();
            tblAdvOrderList.setModel(dm);
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    private void funSelectAdvOrderForBilling()
    {
        try
        {
            int i = tblAdvOrderList.getSelectedRow();
            String advOrderNo=tblAdvOrderList.getModel().getValueAt(i, 0).toString();
            objDirectBiller.funSetAdvOrderNo(advOrderNo);
            objDirectBiller.funShowPanel();
            this.setVisible(false);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblAdvOrderList = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();

        tblAdvOrderList.setBackground(new java.awt.Color(204, 255, 255));
        tblAdvOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt No.", "Customer Code", "Receipt Date", "Order Date", "Amt Deposit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdvOrderList.setRowHeight(25);
        tblAdvOrderList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdvOrderListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblAdvOrderList);

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSTransaction/images/imgCommonBtn1.png"))); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSTransaction/images/imgCommonBtnLong2.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblAdvOrderListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdvOrderListMouseClicked
        // TODO add your handling code here:
        funSelectAdvOrderForBilling();
    }//GEN-LAST:event_tblAdvOrderListMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        objDirectBiller.funShowPanel();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAdvOrderList;
    // End of variables declaration//GEN-END:variables
}
