/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.POSTransaction.view;

import com.POSGlobal.controller.clsGlobalVarClass;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.Timer;
import com.POSGlobal.controller.clsUtility;
import com.POSGlobal.controller.clsUtility2;
import com.POSGlobal.view.frmNumericKeyboard;
import com.POSGlobal.view.frmOkPopUp;
import com.mysql.jdbc.Util;
import javax.swing.table.DefaultTableModel;

public class frmDebitCardBulkRecharge extends javax.swing.JFrame
{

    private clsUtility objUtility;
    private clsUtility2 objUtility2;
    private Map<String, String> hmDebitCardType;
    private StringBuilder sqlBuilder;

    /**
     * This method is used to initialize frmRegisterDebitCard
     */
    public frmDebitCardBulkRecharge()
    {
	initComponents();
	try
	{
	    Timer timer = new Timer(500, new ActionListener()
	    {
		@Override
		public void actionPerformed(ActionEvent e)
		{
		    Date date1 = new Date();
		    String newstr = String.format("%tr", date1);
		    String dateAndTime = clsGlobalVarClass.gPOSDateToDisplay + " " + newstr;
		    lblDate.setText(dateAndTime);
		}
	    });
	    timer.setRepeats(true);
	    timer.setCoalesce(true);
	    timer.setInitialDelay(0);
	    timer.start();

	    lblUserCode.setText(clsGlobalVarClass.gUserCode);
	    lblPosName.setText(clsGlobalVarClass.gPOSName);
	    lblModuleName.setText(clsGlobalVarClass.gSelectedModule);

	    java.util.Date dt = new java.util.Date();
	    int day = dt.getDate();
	    int month = dt.getMonth() + 1;
	    int year = dt.getYear() + 1900;
	    String dte = day + "-" + month + "-" + year;
	    lblDate.setText(clsGlobalVarClass.gPOSDateToDisplay);
	    java.util.Date date = new SimpleDateFormat("dd-MM-yyyy").parse(dte);

	    objUtility = new clsUtility();
	    objUtility2 = new clsUtility2();

	    sqlBuilder = new StringBuilder();
	    hmDebitCardType = new HashMap<String, String>();

	    DefaultTableModel defaultTableModel = ((DefaultTableModel) tblBulkRecharge.getModel());
	    defaultTableModel.setRowCount(0);

	    sqlBuilder.setLength(0);
	    sqlBuilder.append("select strCardTypeCode,strCardName,strCustomerCompulsory "
		    + "from tbldebitcardtype where strClientCode='" + clsGlobalVarClass.gClientCode + "'");
	    ResultSet rsFillComboBox = clsGlobalVarClass.dbMysql.executeResultSet(sqlBuilder.toString());
	    cmbCardType.addItem("");
	    while (rsFillComboBox.next())
	    {
		hmDebitCardType.put(rsFillComboBox.getString(2), rsFillComboBox.getString(1));
		cmbCardType.addItem(rsFillComboBox.getString(2));
	    }
	    rsFillComboBox.close();

	    funSetShortCutKeys();

	}
	catch (Exception e)
	{
	    objUtility.funWriteErrorLog(e);
	    e.printStackTrace();
	}
    }

    private void funSetShortCutKeys()
    {
	btnCancel.setMnemonic('c');
	btnRecharge.setMnemonic('s');
	btnReset.setMnemonic('r');

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelHeader = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        lblModuleName = new javax.swing.JLabel();
        lblformName = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblPosName = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblUserCode = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblHOSign = new javax.swing.JLabel();
        panelLayout = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    getClass().getResource("/com/POSMaster/images/imgBGJPOS.png"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };  
        ;
        panelBody = new javax.swing.JPanel();
        lblCardType = new javax.swing.JLabel();
        cmbCardType = new javax.swing.JComboBox();
        btnRecharge = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblCardStatus = new javax.swing.JLabel();
        lblManualNo = new javax.swing.JLabel();
        txtFromSrNo = new javax.swing.JTextField();
        lblManualNo1 = new javax.swing.JLabel();
        txtToSrNo = new javax.swing.JTextField();
        lblManualNo2 = new javax.swing.JLabel();
        txtRechargeAmt = new javax.swing.JTextField();
        btnAddRecharge = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBulkRecharge = new javax.swing.JTable();
        btnRemoveRecharge = new javax.swing.JButton();
        lblRemarks = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(69, 164, 238));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblProductName.setText("SPOS - ");
        panelHeader.add(lblProductName);

        lblModuleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModuleName.setForeground(new java.awt.Color(255, 255, 255));
        panelHeader.add(lblModuleName);

        lblformName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblformName.setForeground(new java.awt.Color(255, 255, 255));
        lblformName.setText("- Bulk Recharge Debit Card");
        panelHeader.add(lblformName);
        panelHeader.add(filler4);
        panelHeader.add(filler5);

        lblPosName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPosName.setForeground(new java.awt.Color(255, 255, 255));
        lblPosName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosName.setMaximumSize(new java.awt.Dimension(321, 30));
        lblPosName.setMinimumSize(new java.awt.Dimension(321, 30));
        lblPosName.setPreferredSize(new java.awt.Dimension(321, 30));
        panelHeader.add(lblPosName);
        panelHeader.add(filler6);

        lblUserCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserCode.setForeground(new java.awt.Color(255, 255, 255));
        lblUserCode.setMaximumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setMinimumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setPreferredSize(new java.awt.Dimension(90, 30));
        panelHeader.add(lblUserCode);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setMaximumSize(new java.awt.Dimension(192, 30));
        lblDate.setMinimumSize(new java.awt.Dimension(192, 30));
        lblDate.setPreferredSize(new java.awt.Dimension(192, 30));
        panelHeader.add(lblDate);

        lblHOSign.setMaximumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setMinimumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setPreferredSize(new java.awt.Dimension(34, 30));
        panelHeader.add(lblHOSign);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelLayout.setBackground(new java.awt.Color(255, 255, 255));
        panelLayout.setOpaque(false);
        panelLayout.setLayout(new java.awt.GridBagLayout());

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelBody.setMinimumSize(new java.awt.Dimension(800, 570));
        panelBody.setOpaque(false);

        lblCardType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCardType.setText("Debit Card Type : ");

        cmbCardType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbCardTypeActionPerformed(evt);
            }
        });
        cmbCardType.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cmbCardTypeKeyPressed(evt);
            }
        });

        btnRecharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRecharge.setForeground(new java.awt.Color(255, 255, 255));
        btnRecharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn1.png"))); // NOI18N
        btnRecharge.setText("RECHARGE");
        btnRecharge.setToolTipText("Save Debit Crd Detail");
        btnRecharge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecharge.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn2.png"))); // NOI18N
        btnRecharge.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnRechargeMouseClicked(evt);
            }
        });
        btnRecharge.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRechargeActionPerformed(evt);
            }
        });
        btnRecharge.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnRechargeKeyPressed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn1.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.setToolTipText("Reset All Fields");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn2.png"))); // NOI18N
        btnReset.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnResetActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn1.png"))); // NOI18N
        btnCancel.setText("CLOSE");
        btnCancel.setToolTipText("Close Debit Card Registration");
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn2.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        lblManualNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblManualNo.setText("From Sr. No:");

        lblManualNo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblManualNo1.setText("To Sr. No:");

        lblManualNo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblManualNo2.setText("Amount :");

        txtRechargeAmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtRechargeAmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRechargeAmt.setText("0.00");
        txtRechargeAmt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                txtRechargeAmtMouseClicked(evt);
            }
        });

        btnAddRecharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddRecharge.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRecharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn1.png"))); // NOI18N
        btnAddRecharge.setText("ADD");
        btnAddRecharge.setToolTipText("Save Debit Crd Detail");
        btnAddRecharge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddRecharge.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn2.png"))); // NOI18N
        btnAddRecharge.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnAddRechargeMouseClicked(evt);
            }
        });
        btnAddRecharge.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddRechargeActionPerformed(evt);
            }
        });
        btnAddRecharge.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAddRechargeKeyPressed(evt);
            }
        });

        tblBulkRecharge.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblBulkRecharge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Debit Card Manual No", "Amount", "Remarks", "Type Code", "Card No", "Card String"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblBulkRecharge.setRowHeight(25);
        tblBulkRecharge.setSelectionBackground(new java.awt.Color(15, 131, 240));
        tblBulkRecharge.setSelectionForeground(new java.awt.Color(254, 254, 254));
        tblBulkRecharge.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblBulkRecharge.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblBulkRecharge);
        if (tblBulkRecharge.getColumnModel().getColumnCount() > 0)
        {
            tblBulkRecharge.getColumnModel().getColumn(0).setResizable(false);
            tblBulkRecharge.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblBulkRecharge.getColumnModel().getColumn(1).setResizable(false);
            tblBulkRecharge.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblBulkRecharge.getColumnModel().getColumn(2).setResizable(false);
            tblBulkRecharge.getColumnModel().getColumn(2).setPreferredWidth(600);
            tblBulkRecharge.getColumnModel().getColumn(3).setResizable(false);
            tblBulkRecharge.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblBulkRecharge.getColumnModel().getColumn(4).setResizable(false);
            tblBulkRecharge.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblBulkRecharge.getColumnModel().getColumn(5).setResizable(false);
            tblBulkRecharge.getColumnModel().getColumn(5).setPreferredWidth(0);
        }

        btnRemoveRecharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveRecharge.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveRecharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn1.png"))); // NOI18N
        btnRemoveRecharge.setText("REMOVE");
        btnRemoveRecharge.setToolTipText("Save Cost Center Master");
        btnRemoveRecharge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoveRecharge.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgCmnBtn2.png"))); // NOI18N
        btnRemoveRecharge.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnRemoveRechargeMouseClicked(evt);
            }
        });
        btnRemoveRecharge.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveRechargeActionPerformed(evt);
            }
        });
        btnRemoveRecharge.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnRemoveRechargeKeyPressed(evt);
            }
        });

        lblRemarks.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRemarks.setText("Remarks    :");

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRemarks))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelBodyLayout.createSequentialGroup()
                                .addComponent(lblCardType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCardType, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBodyLayout.createSequentialGroup()
                                .addComponent(lblManualNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFromSrNo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblManualNo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtToSrNo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblManualNo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRechargeAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAddRecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveRecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                        .addComponent(btnRecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCardStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCardType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManualNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFromSrNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManualNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtToSrNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManualNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRechargeAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblCardStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(320, Short.MAX_VALUE))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddRecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveRecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        panelLayout.add(panelBody, new java.awt.GridBagConstraints());

        getContentPane().add(panelLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCardTypeActionPerformed

    }//GEN-LAST:event_cmbCardTypeActionPerformed

    private void btnRechargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechargeMouseClicked

    }//GEN-LAST:event_btnRechargeMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked

    }//GEN-LAST:event_btnResetMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
	// TODO add your handling code here:
	dispose();
	clsGlobalVarClass.hmActiveForms.remove("Debit Card Bulk Recharge");
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

	dispose();
	clsGlobalVarClass.hmActiveForms.remove("Debit Card Bulk Recharge");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbCardTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCardTypeKeyPressed


    }//GEN-LAST:event_cmbCardTypeKeyPressed

    private void btnRechargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRechargeKeyPressed

    }//GEN-LAST:event_btnRechargeKeyPressed

    private void btnRechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechargeActionPerformed
	funRechargeButtonClicked();
    }//GEN-LAST:event_btnRechargeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

	funResetButtonClicked();
    }//GEN-LAST:event_btnResetActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
	// TODO add your handling code here:
	clsGlobalVarClass.hmActiveForms.remove("Debit Card Bulk Recharge");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
	// TODO add your handling code here:
	clsGlobalVarClass.hmActiveForms.remove("Debit Card Bulk Recharge");
    }//GEN-LAST:event_formWindowClosing

    private void btnAddRechargeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAddRechargeMouseClicked
    {//GEN-HEADEREND:event_btnAddRechargeMouseClicked
	// TODO add your handling code here:
    }//GEN-LAST:event_btnAddRechargeMouseClicked

    private void btnAddRechargeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddRechargeActionPerformed
    {//GEN-HEADEREND:event_btnAddRechargeActionPerformed
	funAddButtonClicked();
    }//GEN-LAST:event_btnAddRechargeActionPerformed

    private void btnAddRechargeKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAddRechargeKeyPressed
    {//GEN-HEADEREND:event_btnAddRechargeKeyPressed
	// TODO add your handling code here:
    }//GEN-LAST:event_btnAddRechargeKeyPressed

    private void btnRemoveRechargeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRemoveRechargeMouseClicked
    {//GEN-HEADEREND:event_btnRemoveRechargeMouseClicked
	// TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveRechargeMouseClicked

    private void btnRemoveRechargeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveRechargeActionPerformed
    {//GEN-HEADEREND:event_btnRemoveRechargeActionPerformed

	funRemoveButtonClicked();
    }//GEN-LAST:event_btnRemoveRechargeActionPerformed

    private void btnRemoveRechargeKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnRemoveRechargeKeyPressed
    {//GEN-HEADEREND:event_btnRemoveRechargeKeyPressed
	// TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveRechargeKeyPressed

    private void txtRechargeAmtMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtRechargeAmtMouseClicked
    {//GEN-HEADEREND:event_txtRechargeAmtMouseClicked
	try
	{

	    if (txtRechargeAmt.getText().length() == 0)
	    {
		new frmNumericKeyboard(this, true, "", "Double", "Enter recharge amount").setVisible(true);
		txtRechargeAmt.setText(clsGlobalVarClass.gNumerickeyboardValue);
	    }
	    else
	    {
		new frmNumericKeyboard(this, true, txtRechargeAmt.getText(), "Double", "Enter recharge amount").setVisible(true);
		txtRechargeAmt.setText(clsGlobalVarClass.gNumerickeyboardValue);
	    }

	}
	catch (Exception e)
	{
	    objUtility.funWriteErrorLog(e);
	    e.printStackTrace();
	}
    }//GEN-LAST:event_txtRechargeAmtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRecharge;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRecharge;
    private javax.swing.JButton btnRemoveRecharge;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cmbCardType;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCardStatus;
    private javax.swing.JLabel lblCardType;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHOSign;
    private javax.swing.JLabel lblManualNo;
    private javax.swing.JLabel lblManualNo1;
    private javax.swing.JLabel lblManualNo2;
    private javax.swing.JLabel lblModuleName;
    private javax.swing.JLabel lblPosName;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblUserCode;
    private javax.swing.JLabel lblformName;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLayout;
    private javax.swing.JTable tblBulkRecharge;
    private javax.swing.JTextField txtFromSrNo;
    private javax.swing.JTextField txtRechargeAmt;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtToSrNo;
    // End of variables declaration//GEN-END:variables

    private void funAddButtonClicked()
    {
	try
	{
	    if (cmbCardType.getSelectedItem() == null || cmbCardType.getSelectedItem().toString().trim().isEmpty())
	    {
		new frmOkPopUp(this, "Please select card type", "", 1).setVisible(true);
		cmbCardType.requestFocus();
		return;
	    }
	    String debitCardTypeName = cmbCardType.getSelectedItem().toString();
	    String debitCardTypeCode = hmDebitCardType.get(debitCardTypeName);

	    double rechargeAmt = Double.parseDouble(txtRechargeAmt.getText().trim());
	    if (rechargeAmt == 0)
	    {
		new frmOkPopUp(this, "Please enter amount", "", 1).setVisible(true);
		txtRechargeAmt.requestFocus();

		return;
	    }

	    String fromSrNo = txtFromSrNo.getText().trim();
	    String toSrNo = txtToSrNo.getText().trim();

	    String remarks = txtRemarks.getText().trim();
	    if (remarks.isEmpty())
	    {
		new frmOkPopUp(this, "Please enter remarks", "", 1).setVisible(true);
		txtRemarks.requestFocus();

		return;
	    }

	    DefaultTableModel defaultTableModel = ((DefaultTableModel) tblBulkRecharge.getModel());
	    defaultTableModel.setRowCount(0);

	    sqlBuilder.setLength(0);
	    sqlBuilder.append("select a.strCardTypeCode,a.strCardName,b.strCardNo,b.strManualNo,b.strCardString,b.dblRedeemAmt "
		    + "from tbldebitcardtype a,tbldebitcardmaster b "
		    + "where a.strCardTypeCode=b.strCardTypeCode "
		    + "and b.strStatus='Active' "
		    + "and b.strManualNo!='NA' "
		    + "and b.strCardTypeCode='" + debitCardTypeCode + "'  ");
	    if (!fromSrNo.isEmpty() && !toSrNo.isEmpty())
	    {
		sqlBuilder.append("and b.strManualNo between " + fromSrNo + " and " + toSrNo + " ");
	    }
	    ResultSet rsDebitCards = clsGlobalVarClass.dbMysql.executeResultSet(sqlBuilder.toString());
	    while (rsDebitCards.next())
	    {
		Object row[] =
		{
		    rsDebitCards.getString(4), rechargeAmt, remarks, rsDebitCards.getString(1), rsDebitCards.getString(3), rsDebitCards.getString(5)
		};

		defaultTableModel.addRow(row);
	    }
	    rsDebitCards.clearWarnings();

	}
	catch (NumberFormatException n)
	{
	    new frmOkPopUp(this, "Please enter amount", "", 1).setVisible(true);
	    txtRechargeAmt.requestFocus();
	    n.printStackTrace();
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
    }

    private void funResetButtonClicked()
    {
	cmbCardType.setSelectedIndex(0);
	txtFromSrNo.setText("");
	txtToSrNo.setText("");
	txtRechargeAmt.setText("0.00");
	txtRemarks.setText("");

	DefaultTableModel defaultTableModel = ((DefaultTableModel) tblBulkRecharge.getModel());
	defaultTableModel.setRowCount(0);

    }

    private void funRemoveButtonClicked()
    {
	int selectedRows[] = tblBulkRecharge.getSelectedRows();
	DefaultTableModel defaultTableModel = ((DefaultTableModel) tblBulkRecharge.getModel());

	for (int i = 0; i < selectedRows.length; i++)
	{
	    defaultTableModel.removeRow(selectedRows[i]);
	}
    }

    private void funRechargeButtonClicked()
    {
	try
	{
	    int rowCount = tblBulkRecharge.getRowCount();
	    if (rowCount <= 0)
	    {
		new frmOkPopUp(this, "Please add recharge details", "", 1).setVisible(true);
		txtRechargeAmt.requestFocus();

		return;
	    }

	    String settlementCode = "", settlementDesc = "", settlementType = "";
	    sqlBuilder.setLength(0);
	    sqlBuilder.append("select a.strSettelmentCode,a.strSettelmentDesc,a.strSettelmentType "
		    + "from tblsettelmenthd a "
		    + "where a.strSettelmentType='Cash' "
		    + "limit 1");
	    ResultSet rsSettlement = clsGlobalVarClass.dbMysql.executeResultSet(sqlBuilder.toString());
	    if (rsSettlement.next())
	    {
		settlementCode = rsSettlement.getString(1);
		settlementDesc = rsSettlement.getString(2);
		settlementType = rsSettlement.getString(3);
	    }
	    else
	    {
		new frmOkPopUp(this, "No cash settlement found", "", 1).setVisible(true);
		return;
	    }

	    for (int row = 0; row < rowCount; row++)
	    {
		String debitCardManualNo = tblBulkRecharge.getValueAt(row, 0).toString();
		double rechargeAmt = Double.parseDouble(tblBulkRecharge.getValueAt(row, 1).toString());
		String remarks = tblBulkRecharge.getValueAt(row, 2).toString();
		remarks = remarks + ",Recharge By " + clsGlobalVarClass.gUserCode;

		String debitCardTypeCode = tblBulkRecharge.getValueAt(row, 3).toString();
		String debitCardNo = tblBulkRecharge.getValueAt(row, 4).toString();
		String debitCardString = tblBulkRecharge.getValueAt(row, 5).toString();

		String recahrgeNoToInsert = objUtility2.funGetRechargeNo();
		String redeemNoToInsert = objUtility2.funGetRedeemNo();
		String rechargeSlipNoToInsert = objUtility2.funGetRechargeSlipNo();

		String redeemable = "N", complementary = "N";
		String memberCodeForRecharge = "";

		sqlBuilder.setLength(0);
		sqlBuilder.append("insert into tbldebitcardrecharge (intRechargeNo,intRedeemNo,strCardTypeCode,strCardString,"
			+ "strRedeemable,strComplementary,dblRechargeAmount,strUserCreated,dteDateCreated,"
			+ "strPOSCode,strRemarks,strRechargeType,strClientCode,strMemberCode,strRechargeSlipNo,strCardNo) "
			+ "values ('" + recahrgeNoToInsert + "','" + redeemNoToInsert + "','" + debitCardTypeCode + "'"
			+ ",'" + debitCardString + "','" + redeemable + "','" + complementary + "','" + rechargeAmt + "'"
			+ ",'" + clsGlobalVarClass.gUserCode + "','" + objUtility.funGetPOSDateForTransaction() + "'"
			+ ",'" + clsGlobalVarClass.gPOSCode + "','" + remarks + "','Cash'"
			+ ",'" + clsGlobalVarClass.gClientCode + "','" + memberCodeForRecharge + "'"
			+ ",'" + rechargeSlipNoToInsert + "','" + debitCardNo + "')");
		clsGlobalVarClass.dbMysql.execute(sqlBuilder.toString());

		sqlBuilder.setLength(0);
		sqlBuilder.append("insert into tbldcrechargesettlementdtl "
			+ "(strRechargeNo,strSettlementCode,dblRechargeAmt,strCardNo,strType,strClientCode,strDataPostFlag) "
			+ "values('" + recahrgeNoToInsert + "','" + settlementCode + "'"
			+ "," + rechargeAmt + ",'" + debitCardNo + "'"
			+ ",'" + settlementType + "','" + clsGlobalVarClass.gClientCode + "','N') ");
		clsGlobalVarClass.dbMysql.execute(sqlBuilder.toString());

		sqlBuilder.setLength(0);
		sqlBuilder.append("update tbldebitcardmaster "
			+ " set dblRedeemAmt=dblRedeemAmt+" + rechargeAmt + ""
			+ " ,strReachrgeRemark='" + remarks + "'"
			+ " ,strRefMemberCode='" + memberCodeForRecharge + "' "
			+ " where strCardNo='" + debitCardNo + "' "
			+ " and strManualNo='" + debitCardManualNo + "' "
			+ " and strCardTypeCode='" + debitCardTypeCode + "' ");
		clsGlobalVarClass.dbMysql.execute(sqlBuilder.toString());
	    }

	    new frmOkPopUp(this, "Recharge Successful", "Successful", 3).setVisible(true);
	    
	    funResetButtonClicked();

	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
    }

}
