/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.POSTransaction.view;

import com.POSGlobal.controller.clsBenowIntegration;
import com.POSGlobal.controller.clsGlobalVarClass;
import com.POSGlobal.controller.clsRewards;
import com.POSGlobal.controller.clsUPIBean;
import com.POSGlobal.controller.clsUtility;
import com.POSGlobal.view.frmOkPopUp;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class frmShowUPITransactions extends javax.swing.JFrame
{

    private panelShowBills objShowBills;

    private clsUtility objUtility;
    private List<clsUPIBean> objShowUPITransactions;

    public frmShowUPITransactions(panelShowBills objShowBills, List<clsUPIBean> objShowUPITransactions)
    {
	initComponents();
	try
	{
	    this.objShowBills = objShowBills;

	    this.objUtility = new clsUtility();
	    this.objShowUPITransactions = objShowUPITransactions;

	    funFillGridWithItems(objShowUPITransactions);
	}
	catch (Exception e)
	{
	    objUtility.funWriteErrorLog(e);
	    e.printStackTrace();
	}
    }


    public void funFillGridWithItems(List<clsUPIBean> objShowUPITransactions) throws Exception
    {

	DefaultTableModel dtm = new DefaultTableModel()
	{
	    @Override
	    public boolean isCellEditable(int row, int column)
	    {
		//all cells false
		return false;
	    }
	};
	dtm.setRowCount(0);
	dtm.addColumn("MERCHANT CODE");
	dtm.addColumn("REFRENCE NO.");
	dtm.addColumn("PAYMENT STATUS");
	dtm.addColumn("TRANSACTION ID");
	dtm.addColumn("TRANSACTION DATE");
	dtm.addColumn("AMT");
	dtm.addColumn("CUST REF");
	dtm.addColumn("PAY METHOD TYPE");
	dtm.addColumn("PAYER");
	

	for (clsUPIBean objUPIBean : objShowUPITransactions)
	{

	    Object[] ob =
	    {
		objUPIBean.getStrMerchantCode(), objUPIBean.getStrReferenceNo(), objUPIBean.getStrPaymentStatus(), objUPIBean.getStrTransactionId(), objUPIBean.getSttTransactionDate(),objUPIBean.getDblAmount(),objUPIBean.getStrCustomerRefNo(),objUPIBean.getPaymentMethodType(),objUPIBean.getPayer()
	    };
	    dtm.addRow(ob);
	}

	DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
	rightRenderer.setHorizontalAlignment(JLabel.RIGHT);

	tblRewards.setModel(dtm);
	tblRewards.setRowHeight(30);

	tblRewards.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

//        tblBillItems.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
//        tblBillItems.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
	tblRewards.getColumnModel().getColumn(0).setPreferredWidth(100);//id
	tblRewards.getColumnModel().getColumn(1).setPreferredWidth(100);//name
	tblRewards.getColumnModel().getColumn(2).setPreferredWidth(100);//category
	tblRewards.getColumnModel().getColumn(3).setPreferredWidth(100);//reward points
	tblRewards.getColumnModel().getColumn(4).setPreferredWidth(100);//points
	tblRewards.getColumnModel().getColumn(5).setPreferredWidth(100);//points
	tblRewards.getColumnModel().getColumn(6).setPreferredWidth(100);//points
	tblRewards.getColumnModel().getColumn(7).setPreferredWidth(100);//points
	tblRewards.getColumnModel().getColumn(8).setPreferredWidth(100);//points
	

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelLayout = 	new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    getClass().getResource("/com/POSMaster/images/imgBGJPOS.png"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };  ;
        panelHeader = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        lblModuleName = new javax.swing.JLabel();
        lblformName = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblMobileNo = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        panelBody = 	new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    getClass().getResource("/com/POSMaster/images/imgBGJPOS.png"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };  ;
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRewards = new javax.swing.JTable();

        panelLayout.setBackground(new java.awt.Color(255, 255, 255));
        panelLayout.setOpaque(false);
        panelLayout.setPreferredSize(new java.awt.Dimension(520, 470));

        javax.swing.GroupLayout panelLayoutLayout = new javax.swing.GroupLayout(panelLayout);
        panelLayout.setLayout(panelLayoutLayout);
        panelLayoutLayout.setHorizontalGroup(
            panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayoutLayout.setVerticalGroup(
            panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(69, 164, 238));
        panelHeader.setPreferredSize(new java.awt.Dimension(580, 30));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                panelHeaderMouseDragged(evt);
            }
        });

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));

        lblModuleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModuleName.setForeground(new java.awt.Color(255, 255, 255));

        lblformName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblformName.setForeground(new java.awt.Color(255, 255, 255));
        lblformName.setText("Last UPI Transaction: ");

        lblMobileNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMobileNo.setForeground(new java.awt.Color(255, 255, 255));

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(lblProductName)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModuleName)
                    .addComponent(lblformName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblformName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblProductName))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblModuleName))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblMobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelBody.setAutoscrolls(true);
        panelBody.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBody.setMinimumSize(new java.awt.Dimension(520, 470));
        panelBody.setName(""); // NOI18N
        panelBody.setOpaque(false);
        panelBody.setPreferredSize(new java.awt.Dimension(630, 484));

        btnClose.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        tblRewards.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tblRewards.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "MERCHANT CODE", "REF NO.", "PAYMENT STATUS", "TRANSACTION ID", "TRANSACTION DATE", "AMT", "CUST REF NO", "PAY METHOD TYPE"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblRewards.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblRewards.setColumnSelectionAllowed(true);
        tblRewards.setRowHeight(30);
        tblRewards.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRewards.getTableHeader().setReorderingAllowed(false);
        tblRewards.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblRewardsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRewards);
        tblRewards.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblRewards.getColumnModel().getColumnCount() > 0)
        {
            tblRewards.getColumnModel().getColumn(0).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(0).setMaxWidth(100);
            tblRewards.getColumnModel().getColumn(1).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(1).setMaxWidth(100);
            tblRewards.getColumnModel().getColumn(2).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(2).setMaxWidth(100);
            tblRewards.getColumnModel().getColumn(3).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(3).setMaxWidth(100);
            tblRewards.getColumnModel().getColumn(4).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(4).setMaxWidth(100);
            tblRewards.getColumnModel().getColumn(5).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(5).setMaxWidth(100);
            tblRewards.getColumnModel().getColumn(6).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(6).setMaxWidth(100);
            tblRewards.getColumnModel().getColumn(7).setMinWidth(100);
            tblRewards.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblRewards.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(3, Short.MAX_VALUE))
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
	// TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
	// TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
	// TODO add your handling code here:
	int x = evt.getXOnScreen();
	int y = evt.getYOnScreen();
	this.setLocation(x, y);
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
	// TODO add your handling code here:
	dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
	// TODO add your handling code here:
	dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void tblRewardsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRewardsMouseClicked
	
	int rowNo=tblRewards.getSelectedRow();
	String merchantCode = tblRewards.getValueAt(rowNo, 0).toString();
	String paidAmount = tblRewards.getValueAt(rowNo, 5).toString();
	String txnRefNumber = tblRewards.getValueAt(rowNo, 3).toString();
	
	String strBillNo = JOptionPane.showInputDialog(null, "Enter Bill Number:");
	
	
	clsBenowIntegration objBenowIntegration = new clsBenowIntegration();
	if(!strBillNo.isEmpty()&&!txnRefNumber.isEmpty()&&paidAmount !="0.00"){
	    if(funCheckBillNo(strBillNo)){
		String status = objBenowIntegration.funUpdateBillNoToBenow(paidAmount,txnRefNumber,strBillNo);
		    if(status.equalsIgnoreCase("true"))
		    {
		       JOptionPane.showMessageDialog(this, " Bill No ("+strBillNo+") Linked to "+tblRewards.getValueAt(rowNo, 8).toString()); 
		    }   
		    else
		    {
			JOptionPane.showMessageDialog(this, "Bill Updation Failed"); 
		    }  	
	    }else{
		JOptionPane.showMessageDialog(this, "Invalid Bill No "); 
	    }
	      
	}
	else
	    {
		JOptionPane.showMessageDialog(this, "Please Check Details"); 
	    }
	    
    }//GEN-LAST:event_tblRewardsMouseClicked

    private boolean funCheckBillNo(String strBillNO){
	
	boolean isBillPresent=false;
	try{
	String sql="select count( a.strBillNo) from tblbillhd a where a.strBillNo='"+strBillNO+"'";
	ResultSet rs=clsGlobalVarClass.dbMysql.executeResultSet(sql);
	    if(rs.next()){
		if(rs.getInt(1)>0){
		    isBillPresent=true;
		}
	    }
	}catch(Exception e){
	    e.printStackTrace();
	}
	return isBillPresent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblMobileNo;
    private javax.swing.JLabel lblModuleName;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblformName;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLayout;
    private javax.swing.JTable tblRewards;
    // End of variables declaration//GEN-END:variables
   
}
