/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.POSTransaction.view;

import com.POSGlobal.controller.clsTDHOnItemDtl;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class panelSubItem extends javax.swing.JPanel
{

    frmMakeKOT objMakeKOT;
    frmDirectBiller objDirectBiller;
    frmAdvanceOrder objAdvOrder;
    Object obj;
    ResultSet rs;
    //private String PosCode, amount, itemcode, sql, rate, ModifierName, modifierdesc, SubItemName, SubItemCode;
    private String className;
    int count;
    private String tdhItemCode;

    public panelSubItem(Object Obj)
    {
        try
        {
            initComponents();
            obj = Obj;
            className = Obj.getClass().getName();
            System.out.println("class Name =" + className);
            if (className.equals("com.POSTransaction.view.frmMakeKOT"))
            {
                objMakeKOT = (frmMakeKOT) Obj;
            }
            else
            {
                objDirectBiller = (frmDirectBiller) Obj;
            }

        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    public void getItem(String textValue)
    {
        try
        {
            tdhItemCode = textValue;
            fillTable(textValue);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    public void fillTable(String Itemcode)
    {
        try
        {
            DefaultTableModel dm = (DefaultTableModel) tblSubItemTable.getModel();
            dm.setRowCount(0);
            List<clsTDHOnItemDtl.subItemDtl> ItemList = clsTDHOnItemDtl.hm_ComboItemDtl.get(Itemcode);
            for (clsTDHOnItemDtl.subItemDtl ob : ItemList)
            {
                String temp_SubItemName = ob.getstrSubItemName();
                String temp_SubItemCode = ob.getStrSubItemCode();
                int temp_SubMaxQty = (int) ob.getIntSubItemQty();
                Object[] rows =
                {
                    temp_SubItemName, temp_SubItemCode, temp_SubMaxQty
                };
                dm.addRow(rows);
            }
            tblSubItemTable.setModel(dm);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        SubItemScrollPane = new javax.swing.JScrollPane();
        tblSubItemTable = new javax.swing.JTable();
        btnCloseSubItemPannel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 235, 174)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSubItemTable.setBackground(new java.awt.Color(51, 102, 255));
        tblSubItemTable.setForeground(new java.awt.Color(255, 255, 255));
        tblSubItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "SubItemName", "SubItemCode", "Max Sub Item QTY"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblSubItemTable.setRowHeight(25);
        tblSubItemTable.getTableHeader().setReorderingAllowed(false);
        tblSubItemTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblSubItemTableMouseClicked(evt);
            }
        });
        SubItemScrollPane.setViewportView(tblSubItemTable);
        if (tblSubItemTable.getColumnModel().getColumnCount() > 0)
        {
            tblSubItemTable.getColumnModel().getColumn(0).setResizable(false);
            tblSubItemTable.getColumnModel().getColumn(1).setResizable(false);
            tblSubItemTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(SubItemScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 49, 341, 410));

        btnCloseSubItemPannel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCloseSubItemPannel.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseSubItemPannel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSTransaction/images/imgCommonBtn1.png"))); // NOI18N
        btnCloseSubItemPannel.setText("Close");
        btnCloseSubItemPannel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseSubItemPannel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSTransaction/images/imgCommonBtn2.png"))); // NOI18N
        btnCloseSubItemPannel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseSubItemPannelActionPerformed(evt);
            }
        });
        add(btnCloseSubItemPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseSubItemPannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSubItemPannelActionPerformed
        // TODO add your handling code here:
        try
        {
            setVisible(false);
            if (className.equals("com.POSTransaction.view.frmMakeKOT"))
            {
                objMakeKOT = (frmMakeKOT) obj;
                objMakeKOT.funShowPanel();
                // globalVarClass.gflagforSubItem = false;
            }
            else
            {
                objDirectBiller = (frmDirectBiller) obj;
                objDirectBiller.funShowPanel();                
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCloseSubItemPannelActionPerformed

    private void tblSubItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSubItemTableMouseClicked
        // TODO add your handling code here:
        try
        {
            if (tblSubItemTable.getRowCount() > 0)
            {
                String tempItemName, tempItemCode;
                int selecteRow;
                double tempMaxThisSubItemLimit;
                selecteRow = tblSubItemTable.getSelectedRow();
                tempItemName = tblSubItemTable.getValueAt(selecteRow, 0).toString();
                tempItemCode = tblSubItemTable.getValueAt(selecteRow, 1).toString();
                tempMaxThisSubItemLimit = Double.parseDouble(tblSubItemTable.getValueAt(selecteRow, 2).toString());
                if (className.equals("com.POSTransaction.view.frmMakeKOT"))
                {
                    // make KOT form Code   
                    objMakeKOT.funAddSubItems(tempItemCode, tempItemName, tempMaxThisSubItemLimit, tdhItemCode);

                }
                else
                {
                    //direct biller form code  
                    objDirectBiller.funAddSubItems(tempItemCode, tempItemName, tempMaxThisSubItemLimit, tdhItemCode);
                }
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblSubItemTableMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SubItemScrollPane;
    private javax.swing.JButton btnCloseSubItemPannel;
    private javax.swing.JTable tblSubItemTable;
    // End of variables declaration//GEN-END:variables
}
