package com.POSGlobal.view;

import com.POSGlobal.controller.clsGlobalVarClass;
import com.POSGlobal.controller.clsUtility;

public class frmNumericKeyboard extends javax.swing.JDialog
{

    private String textValue = "", passValue = "";
    private String type;
    private clsUtility objUtility;

    public frmNumericKeyboard(java.awt.Frame parent, boolean modal, String existingText, String formType, String title)
    {
        super(parent, modal);
        try
        {
            initComponents();
            objUtility = new clsUtility();
            type = formType;
            setLocationRelativeTo(this);
            lblTitle.setText(title);
            if (!existingText.isEmpty())
            {
                txtDisplayNumber.setText(existingText);
            }
            funSetShortCutKeys();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    private void funSetShortCutKeys()
    {
        btnClose.setMnemonic('c');
    }

    /*
     public frmNumericKeyboard(java.awt.Frame parent, boolean modal, String flag, String title) {
     super(parent, modal);
     try {
     initComponents();
     objUtility=new clsUtility();
     flgFormType = "advorder";
     setLocationRelativeTo(this);
     lblTitle.setText(title);

     } catch (Exception e) {
     e.printStackTrace();
     }
     }

     public frmNumericKeyboard(java.awt.Frame parent, String title, String data) {
     super(parent, true);
     try {
     initComponents();
     objUtility=new clsUtility();
     flgFormType = "master";
     setLocationRelativeTo(this);
     lblTitle.setText(title);
     txtDisplayNumber.requestFocus();
     if (data.trim().length() > 0) {
     txtDisplayNumber.setText(data.trim());
     }

     } catch (Exception e) {
     e.printStackTrace();
     }
     }

     public frmNumericKeyboard(java.awt.Frame parent, boolean modal, String value, String flag, String title) {
     super(parent, modal);
     try {
     initComponents();
     objUtility=new clsUtility();
     flgFormType = "billing";
     setLocationRelativeTo(this);
     lblTitle.setText(title);
     passValue = value;
     txtDisplayNumber.setText(value);
     } catch (Exception e) {
     e.printStackTrace();
     }
     }*/
    private void funOpenCustomerMasterHelp()
    {
        objUtility.funCallForSearchForm("CustomerMaster");
        new frmSearchFormDialog(null, true).setVisible(true);
        if (clsGlobalVarClass.gSearchItemClicked)
        {
            Object[] data = clsGlobalVarClass.gArrListSearchData.toArray();
            //System.out.println("Cust Mb No= "+data[2]);
            clsGlobalVarClass.gSearchItemClicked = false;

            String[] mobileNos = data[2].toString().split(",");
            if (mobileNos.length > 0)
            {
                txtDisplayNumber.setText(mobileNos[0]);
            }
            else
            {
                txtDisplayNumber.setText("");
            }
            funOKButtonClicked();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtDisplayNumber = new javax.swing.JTextField();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        setMinimumSize(new java.awt.Dimension(252, 304));
        setUndecorated(true);
        setResizable(false);

        txtDisplayNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDisplayNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplayNumber.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                txtDisplayNumberMouseClicked(evt);
            }
        });
        txtDisplayNumber.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtDisplayNumberKeyPressed(evt);
            }
        });

        btnNum1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum1.setForeground(new java.awt.Color(255, 255, 255));
        btnNum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum1.setText("1");
        btnNum1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum1MouseClicked(evt);
            }
        });

        btnNum2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum2.setForeground(new java.awt.Color(255, 255, 255));
        btnNum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum2.setText("2");
        btnNum2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum2MouseClicked(evt);
            }
        });

        btnNum3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum3.setForeground(new java.awt.Color(255, 255, 255));
        btnNum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum3.setText("3");
        btnNum3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum3MouseClicked(evt);
            }
        });

        btnNum4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum4.setForeground(new java.awt.Color(255, 255, 255));
        btnNum4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum4.setText("4");
        btnNum4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum4MouseClicked(evt);
            }
        });

        btnNum8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum8.setForeground(new java.awt.Color(255, 255, 255));
        btnNum8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum8.setText("8");
        btnNum8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum8.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum8MouseClicked(evt);
            }
        });

        btnNum7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum7.setForeground(new java.awt.Color(255, 255, 255));
        btnNum7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum7.setText("7");
        btnNum7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum7.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum7MouseClicked(evt);
            }
        });
        btnNum7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNum7ActionPerformed(evt);
            }
        });

        btnNum6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum6.setForeground(new java.awt.Color(255, 255, 255));
        btnNum6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum6.setText("6");
        btnNum6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum6MouseClicked(evt);
            }
        });

        btnNum5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum5.setForeground(new java.awt.Color(255, 255, 255));
        btnNum5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum5.setText("5");
        btnNum5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum5MouseClicked(evt);
            }
        });

        btnNum9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum9.setForeground(new java.awt.Color(255, 255, 255));
        btnNum9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum9.setText("9");
        btnNum9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum9.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum9MouseClicked(evt);
            }
        });

        btnNum0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNum0.setForeground(new java.awt.Color(255, 255, 255));
        btnNum0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnNum0.setText("0");
        btnNum0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNum0.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnNum0.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNum0MouseClicked(evt);
            }
        });

        btnDot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDot.setForeground(new java.awt.Color(255, 255, 255));
        btnDot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnDot.setText(".");
        btnDot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDot.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnDot.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnDotMouseClicked(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnReset.setText("C");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnReset.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnResetMouseClicked(evt);
            }
        });

        btnBackspace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackspace.setForeground(new java.awt.Color(255, 255, 255));
        btnBackspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnBackspace.setText("<-");
        btnBackspace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackspace.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnBackspace.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnBackspaceMouseClicked(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn1.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOK.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgCmnBtn2.png"))); // NOI18N
        btnOK.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOKMouseClicked(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDisplayNumber)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisplayNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        // TODO add your handling code here:
        funOKButtonClicked();
    }//GEN-LAST:event_btnOKMouseClicked

    private void btnNum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum1MouseClicked
        // TODO add your handling code here:
        try
        {
            //textValue+=textValue="1";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "1");
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum1MouseClicked

    private void btnNum2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum2MouseClicked
        // TODO add your handling code here:
        try
        {
            //textValue+=textValue="2";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "2");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum2MouseClicked

    private void btnNum3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum3MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "3";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "3");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum3MouseClicked

    private void btnNum4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum4MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "4";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "4");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum4MouseClicked

    private void btnNum5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum5MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "5";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "5");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum5MouseClicked

    private void btnNum6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum6MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "6";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "6");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum6MouseClicked

    private void btnNum7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum7MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "7";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "7");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum7MouseClicked

    private void btnNum8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum8MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "8";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "8");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum8MouseClicked

    private void btnNum9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum9MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "9";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "9");
            txtDisplayNumber.setText(txtDisplayNumber.getText());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum9MouseClicked

    private void btnNum0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum0MouseClicked
        // TODO add your handling code here:
        try
        {
            textValue += textValue = "0";
            txtDisplayNumber.setText(txtDisplayNumber.getText() + "0");
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNum0MouseClicked

    private void btnBackspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackspaceMouseClicked
        // TODO add your handling code here:
        try
        {
            if (txtDisplayNumber.getText().length() != 0)
            {
                StringBuilder sb = new StringBuilder(txtDisplayNumber.getText());
                sb.delete(txtDisplayNumber.getText().length() - 1, txtDisplayNumber.getText().length());
                String s = sb.toString();
                txtDisplayNumber.setText(s);
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBackspaceMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        try
        {
            textValue = "";
            txtDisplayNumber.setText("");

        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseClicked
        // TODO add your handling code here:
        try
        {
            if (textValue.contains("."))
            {
            }
            else
            {
                textValue += textValue = ".";
                txtDisplayNumber.setText(txtDisplayNumber.getText() + ".");
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDotMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        clsGlobalVarClass.gNumerickeyboardValue = passValue;
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void txtDisplayNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisplayNumberKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '?' || evt.getKeyChar() == '/')
        {
            funOpenCustomerMasterHelp();
        }
        if (evt.getKeyCode() == 10)
        {
            funPressEnterBtn();
        }
    }//GEN-LAST:event_txtDisplayNumberKeyPressed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        clsGlobalVarClass.gNumerickeyboardValue = passValue;
        objUtility = null;
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtDisplayNumberMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtDisplayNumberMouseClicked
    {//GEN-HEADEREND:event_txtDisplayNumberMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2)
        {
            funOpenCustomerMasterHelp();
        }
    }//GEN-LAST:event_txtDisplayNumberMouseClicked

    private void funOKButtonClicked()
    {
        try
        {
            /*
             if (!flgFormType.equals("homedelivery")) {
             if (txtDisplayNumber.getText().trim().length() == 0) {
             clsGlobalVarClass.gNumerickeyboardValue = "0";
             }
             }*/

            if (txtDisplayNumber.getText().trim().length() == 0)
            {
                clsGlobalVarClass.gNumerickeyboardValue = "0";
            }
            funPressEnterBtn();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    public void funPressEnterBtn()
    {
        try
        {
            /*
             if ((!flgFormType.equals("homedelivery")) || (!flgFormType.equals("master"))) 
             {
             if(txtDisplayNumber.getText().isEmpty())
             {
             clsGlobalVarClass.gNumerickeyboardValue = "0";
             }
             else
             {
             if (!clsGlobalVarClass.validateNumbers(txtDisplayNumber.getText().trim())) {
             new frmOkPopUp(null, "Please Enter Numbers Only", "Error", 1).setVisible(true);
             return;
             }
             clsGlobalVarClass.gNumerickeyboardValue=String.valueOf(Math.abs(Double.parseDouble(txtDisplayNumber.getText())));
             //clsGlobalVarClass.gNumerickeyboardValue=String.valueOf(Double.parseDouble(txtDisplayNumber.getText()));
             }
             }*/

            if (txtDisplayNumber.getText().isEmpty())
            {
                clsGlobalVarClass.gNumerickeyboardValue = "0";
            }
            else
            {
                if (!clsGlobalVarClass.validateNumbers(txtDisplayNumber.getText().trim()))
                {
                    new frmOkPopUp(null, "Please Enter Numbers Only", "Error", 1).setVisible(true);
                    return;
                }
                if (type.equalsIgnoreCase("Double"))
                {
                    clsGlobalVarClass.gNumerickeyboardValue = String.valueOf(Math.abs(Double.parseDouble(txtDisplayNumber.getText())));
                }
                else
                {
                    clsGlobalVarClass.gNumerickeyboardValue = String.valueOf(Long.parseLong(txtDisplayNumber.getText()));
                }
            }

            dispose();
            objUtility = null;

        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDisplayNumber;
    // End of variables declaration//GEN-END:variables
}
