/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.POSGlobal.view;

import com.POSGlobal.controller.clsGlobalVarClass;
import com.POSGlobal.controller.clsStructureUpdater;
import com.sanguine.forms.frmConfigSettings;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

public class frmTools extends javax.swing.JFrame
{

    private String callingType = "NA";

    public frmTools(String type)
    {
        initComponents();
        funSetShortCutKeys();

        callingType = type;
        lblUserCode.setText(clsGlobalVarClass.gUserCode);
        lblPosName.setText(clsGlobalVarClass.gPOSName);
        lblDate.setText(clsGlobalVarClass.gPOSDateToDisplay);
        lblModuleName.setText(clsGlobalVarClass.gSelectedModule);
        if ("startup".equals(callingType))
        {
            lblDataBasebackUp.setEnabled(false);
            lblConfigSettings.setEnabled(false);
            lblClose.setEnabled(false);
        }
        if (clsGlobalVarClass.gTheme.equalsIgnoreCase("Default"))
        {
            lblUpdateStructure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgStructureUpdate.png")));
            lblDataBasebackUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgDatabaseBackup.png"))); // NOI18N
            lblConfigSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgConfigSettings.png"))); // NOI18N 

            lblClearTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClearTransaction.png")));
            lblClearMasters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClearMaster.png"))); // NOI18N
            lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClose.png"))); // NOI18N 
        }
        else
        {
            lblUpdateStructure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgStructureUpdate1.png")));
            lblDataBasebackUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgDatabaseBackup1.png"))); // NOI18N
            lblConfigSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgConfigSettings1.png"))); // NOI18N 

            lblClearTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClearTransaction1.png")));
            lblClearMasters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClearMaster1.png"))); // NOI18N
            lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClose1.png"))); // NOI18N 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        lblModuleName = new javax.swing.JLabel();
        lblformName = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblPosName = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblUserCode = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblHOSign = new javax.swing.JLabel();
        panelLayout = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    getClass().getResource("/com/POSGlobal/images/imgBGJPOS.png"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };  
        ;
        panelBody = new javax.swing.JPanel();
        lblUpdateStructure = new javax.swing.JLabel();
        lblDataBasebackUp = new javax.swing.JLabel();
        lblConfigSettings = new javax.swing.JLabel();
        lblClearTransaction = new javax.swing.JLabel();
        lblClearMasters = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(69, 164, 238));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblProductName.setText("SPOS -");
        panelHeader.add(lblProductName);

        lblModuleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModuleName.setForeground(new java.awt.Color(255, 255, 255));
        panelHeader.add(lblModuleName);

        lblformName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblformName.setForeground(new java.awt.Color(255, 255, 255));
        lblformName.setText("- TOOLS");
        panelHeader.add(lblformName);
        panelHeader.add(filler4);
        panelHeader.add(filler5);

        lblPosName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPosName.setForeground(new java.awt.Color(255, 255, 255));
        lblPosName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosName.setMaximumSize(new java.awt.Dimension(321, 30));
        lblPosName.setMinimumSize(new java.awt.Dimension(321, 30));
        lblPosName.setPreferredSize(new java.awt.Dimension(321, 30));
        panelHeader.add(lblPosName);
        panelHeader.add(filler6);

        lblUserCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserCode.setForeground(new java.awt.Color(255, 255, 255));
        lblUserCode.setMaximumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setMinimumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setPreferredSize(new java.awt.Dimension(90, 30));
        panelHeader.add(lblUserCode);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setMaximumSize(new java.awt.Dimension(192, 30));
        lblDate.setMinimumSize(new java.awt.Dimension(192, 30));
        lblDate.setPreferredSize(new java.awt.Dimension(192, 30));
        panelHeader.add(lblDate);

        lblHOSign.setMaximumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setMinimumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setPreferredSize(new java.awt.Dimension(34, 30));
        panelHeader.add(lblHOSign);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelLayout.setOpaque(false);
        panelLayout.setLayout(new java.awt.GridBagLayout());

        panelBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelBody.setMinimumSize(new java.awt.Dimension(800, 570));
        panelBody.setOpaque(false);

        lblUpdateStructure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgStructureUpdate.png"))); // NOI18N
        lblUpdateStructure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateStructureMouseClicked(evt);
            }
        });

        lblDataBasebackUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgDatabaseBackup.png"))); // NOI18N
        lblDataBasebackUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataBasebackUpMouseClicked(evt);
            }
        });

        lblConfigSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgConfigSettings.png"))); // NOI18N
        lblConfigSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfigSettingsMouseClicked(evt);
            }
        });

        lblClearTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClearTransaction.png"))); // NOI18N
        lblClearTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearTransactionMouseClicked(evt);
            }
        });

        lblClearMasters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClearMaster.png"))); // NOI18N
        lblClearMasters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMastersMouseClicked(evt);
            }
        });

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSGlobal/images/imgClose.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClearTransaction)
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addComponent(lblUpdateStructure)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClearMasters)
                    .addComponent(lblDataBasebackUp))
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClose)
                    .addComponent(lblConfigSettings))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateStructure, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataBasebackUp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfigSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClearTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClearMasters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        panelLayout.add(panelBody, new java.awt.GridBagConstraints());

        getContentPane().add(panelLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void funSetShortCutKeys()
    {
        //btnClose.setMnemonic('c');

    }
    private void btnClearTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataBasebackUp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataBasebackUp1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        clsGlobalVarClass.hmActiveForms.remove("Tools");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        clsGlobalVarClass.hmActiveForms.remove("Tools");
    }//GEN-LAST:event_formWindowClosing

    private void lblUpdateStructureMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblUpdateStructureMouseClicked
    {//GEN-HEADEREND:event_lblUpdateStructureMouseClicked

        lblUpdateStructure.setEnabled(false);

        frmOkPopUp objOkPopUp = new frmOkPopUp(this, "It Will Take Some Time..! Press Ok To Countinue", "Message!!", 2);
        objOkPopUp.setVisible(true);

        clsStructureUpdater ob = new clsStructureUpdater();
        ob.structup();
        lblUpdateStructure.setEnabled(true);
        if ("startup".equals(callingType))
        {
            dispose();
            System.exit(1);
        }
    }//GEN-LAST:event_lblUpdateStructureMouseClicked

    private void lblDataBasebackUpMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblDataBasebackUpMouseClicked
    {//GEN-HEADEREND:event_lblDataBasebackUpMouseClicked
        if (lblDataBasebackUp.isEnabled())
        {
            new frmDataBaseBackUp().setVisible(true);
        }
    }//GEN-LAST:event_lblDataBasebackUpMouseClicked

    private void lblConfigSettingsMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblConfigSettingsMouseClicked
    {//GEN-HEADEREND:event_lblConfigSettingsMouseClicked
        try
        {
            new frmConfigSettings().setVisible(true);
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            Logger.getLogger(frmTools.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblConfigSettingsMouseClicked

    private void lblClearTransactionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblClearTransactionMouseClicked
    {//GEN-HEADEREND:event_lblClearTransactionMouseClicked
        new frmClearTransaction().setVisible(true);
    }//GEN-LAST:event_lblClearTransactionMouseClicked

    private void lblClearMastersMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblClearMastersMouseClicked
    {//GEN-HEADEREND:event_lblClearMastersMouseClicked
        new frmClearMaster().setVisible(true);
    }//GEN-LAST:event_lblClearMastersMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblCloseMouseClicked
    {//GEN-HEADEREND:event_lblCloseMouseClicked
        if (lblClose.isEnabled())
        {
            dispose();
            clsGlobalVarClass.hmActiveForms.remove("Tools");

        }
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new frmTools("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel lblClearMasters;
    private javax.swing.JLabel lblClearTransaction;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfigSettings;
    private javax.swing.JLabel lblDataBasebackUp;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHOSign;
    private javax.swing.JLabel lblModuleName;
    private javax.swing.JLabel lblPosName;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblUpdateStructure;
    private javax.swing.JLabel lblUserCode;
    private javax.swing.JLabel lblformName;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLayout;
    // End of variables declaration//GEN-END:variables
}
