/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spos.controller;

import com.POSGlobal.controller.clsGlobalVarClass;
import com.POSGlobal.view.frmOkPopUp;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jai Chandra
 */
public class frmDesktop extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame
     */
    private String sql;

    private ResultSet rs;
    private DefaultTableModel dm1;
    private int SelectedFormRowNo;

    public frmDesktop()
    {
        initComponents();
        try
        {
            lblUserCode.setText(clsGlobalVarClass.gUserCode);
            lblPosName.setText(clsGlobalVarClass.gPOSName);

            Date dt = new Date();
            String currentDate = dt.getDate() + "-" + (dt.getMonth() + 1) + "-" + (dt.getYear() + 1900);
            Timer timer = new Timer(500, new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    tickTock();
                }
            });
            timer.setRepeats(true);
            timer.setCoalesce(true);
            timer.setInitialDelay(0);
            timer.start();
            lblFormName.setText(clsGlobalVarClass.gSelectedModule + " Desktop Sequence");
            funLoadTable();

        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is used to tickTock
     */
    public void tickTock()
    {
        Date date1 = new Date();
//        Date date2 = new Date( );
//        SimpleDateFormat dte =  new SimpleDateFormat ("E yyyy.MM.dd");
        String new_str = String.format("%tr", date1);
        String dateAndTime = clsGlobalVarClass.gPOSDateToDisplay + " " + new_str;
        lblclock.setText(dateAndTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblPosName = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblUserCode = new javax.swing.JLabel();
        lblclock = new javax.swing.JLabel();
        lblHOSign = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tblDesktop = new javax.swing.JTable();
        lblMoveDown = new javax.swing.JLabel();
        lblMoveUp = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblFormName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(69, 164, 238));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblProductName.setText("SPOS - Desktop");
        jPanel1.add(lblProductName);
        jPanel1.add(filler4);
        jPanel1.add(filler5);

        lblPosName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPosName.setForeground(new java.awt.Color(255, 255, 255));
        lblPosName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosName.setMaximumSize(new java.awt.Dimension(321, 30));
        lblPosName.setMinimumSize(new java.awt.Dimension(321, 30));
        lblPosName.setPreferredSize(new java.awt.Dimension(321, 30));
        jPanel1.add(lblPosName);
        jPanel1.add(filler6);

        lblUserCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserCode.setForeground(new java.awt.Color(255, 255, 255));
        lblUserCode.setMaximumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setMinimumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(lblUserCode);

        lblclock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblclock.setForeground(new java.awt.Color(255, 255, 255));
        lblclock.setMaximumSize(new java.awt.Dimension(192, 30));
        lblclock.setMinimumSize(new java.awt.Dimension(192, 30));
        lblclock.setPreferredSize(new java.awt.Dimension(192, 30));
        jPanel1.add(lblclock);

        lblHOSign.setMaximumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setMinimumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel1.add(lblHOSign);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 570));
        jPanel3.setOpaque(false);

        tblDesktop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDesktop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sequence No", "Module Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDesktop.setRowHeight(25);
        tblDesktop.getTableHeader().setReorderingAllowed(false);
        tblDesktop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDesktopMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tblDesktop);

        lblMoveDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgMoveDown.png"))); // NOI18N
        lblMoveDown.setToolTipText("Move Down");
        lblMoveDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMoveDownMouseClicked(evt);
            }
        });

        lblMoveUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgMoveUp.png"))); // NOI18N
        lblMoveUp.setToolTipText("Move Up");
        lblMoveUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMoveUpMouseClicked(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn1.png"))); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.setToolTipText("Close ");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn2.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn1.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setToolTipText("Save Changes");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn2.png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        lblFormName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 69, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(lblMoveUp)
                                .addGap(10, 10, 10)
                                .addComponent(lblMoveDown)))
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoveUp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoveDown, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDesktopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDesktopMouseClicked
        // TODO add your handling code here:
        SelectedFormRowNo = 0;
        SelectedFormRowNo = tblDesktop.getSelectedRow();
    }//GEN-LAST:event_tblDesktopMouseClicked

    private void lblMoveDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoveDownMouseClicked
        if (tblDesktop.getRowCount() == SelectedFormRowNo + 1)
        {
            // do Nothing This is last row
        }
        else
        {
            String tempSelectedFormName = tblDesktop.getValueAt(SelectedFormRowNo, 1).toString();
            String tempLowerFormName = tblDesktop.getValueAt(SelectedFormRowNo + 1, 1).toString();
            tblDesktop.setValueAt(tempSelectedFormName, SelectedFormRowNo + 1, 1);
            tblDesktop.setValueAt(tempLowerFormName, SelectedFormRowNo, 1);
            SelectedFormRowNo = SelectedFormRowNo + 1;
            tblDesktop.setRowSelectionInterval(SelectedFormRowNo, SelectedFormRowNo);

        }
    }//GEN-LAST:event_lblMoveDownMouseClicked

    private void lblMoveUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoveUpMouseClicked
        // TODO add your handling code here:
        if (SelectedFormRowNo == 0)
        {
            //Do nothing This is first row
        }
        else
        {
            String tempSelectedFormName = tblDesktop.getValueAt(SelectedFormRowNo, 1).toString();
            String tempUpperFormName = tblDesktop.getValueAt(SelectedFormRowNo - 1, 1).toString();
            tblDesktop.setValueAt(tempSelectedFormName, SelectedFormRowNo - 1, 1);
            tblDesktop.setValueAt(tempUpperFormName, SelectedFormRowNo, 1);
            SelectedFormRowNo = SelectedFormRowNo - 1;
            tblDesktop.setRowSelectionInterval(SelectedFormRowNo, SelectedFormRowNo);

        }
    }//GEN-LAST:event_lblMoveUpMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        try
        {
            int Exec = 0;
            for (int i = 0; i < tblDesktop.getRowCount(); i++)
            {
                if (clsGlobalVarClass.gSuperUser == true)
                {
                    sql = "update tblsuperuserdtl set intSequence='" + tblDesktop.getValueAt(i, 0) + "' where strFormName='" + tblDesktop.getValueAt(i, 1) + "' and strUserCode='" + clsGlobalVarClass.gUserCode + "'";
                }
                else
                {
                    sql = "update tbluserdtl set intSequence='" + tblDesktop.getValueAt(i, 0) + "' where strFormName='" + tblDesktop.getValueAt(i, 1) + "' and strUserCode='" + clsGlobalVarClass.gUserCode + "'";
                }
                Exec = clsGlobalVarClass.dbMysql.execute(sql);
            }
            if (Exec > 0)
            {
                new frmOkPopUp(this, "Sequence Save Successfully", "Successful", 3).setVisible(true);
                funLoadTable();
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Invalid Selection");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new frmDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFormName;
    private javax.swing.JLabel lblHOSign;
    private javax.swing.JLabel lblMoveDown;
    private javax.swing.JLabel lblMoveUp;
    private javax.swing.JLabel lblPosName;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblUserCode;
    private javax.swing.JLabel lblclock;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblDesktop;
    // End of variables declaration//GEN-END:variables

    private void funLoadTable()
    {
        try
        {
            dm1 = (DefaultTableModel) tblDesktop.getModel();
            dm1.setRowCount(0);
            if (clsGlobalVarClass.gSuperUser == true)
            {
                sql = "select a.intSequence,a.strFormName from tblsuperuserdtl a left outer join tblforms b on a.strFormName=b.strModuleName ";

                if (clsGlobalVarClass.gSelectedModule.equalsIgnoreCase("Masters"))
                {
                    sql = sql + " where a.strUserCode='" + clsGlobalVarClass.gUserCode + "' and b.strModuleType='M'";
                }
                else if (clsGlobalVarClass.gSelectedModule.equalsIgnoreCase("Transactions"))
                {
                    sql = sql + " where a.strUserCode='" + clsGlobalVarClass.gUserCode + "' and b.strModuleType='T'";
                }
                else if (clsGlobalVarClass.gSelectedModule.equalsIgnoreCase("Reports"))
                {
                    sql = sql + " where a.strUserCode='" + clsGlobalVarClass.gUserCode + "' and b.strModuleType='R'";
                }
                sql = sql + " order by a.intSequence;";
            }
            else
            {
                sql = "select a.intSequence,a.strFormName from tbluserdtl a left outer join tblforms b on a.strFormName=b.strModuleName ";

                if (clsGlobalVarClass.gSelectedModule.equalsIgnoreCase("Masters"))
                {
                    sql = sql + " where a.strUserCode='" + clsGlobalVarClass.gUserCode + "' and b.strModuleType='M'";
                }
                else if (clsGlobalVarClass.gSelectedModule.equalsIgnoreCase("Transactions"))
                {
                    sql = sql + " where a.strUserCode='" + clsGlobalVarClass.gUserCode + "' and b.strModuleType='T'";
                }
                else if (clsGlobalVarClass.gSelectedModule.equalsIgnoreCase("Reports"))
                {
                    sql = sql + " where a.strUserCode='" + clsGlobalVarClass.gUserCode + "' and b.strModuleType='R'";
                }
                sql = sql + " order by a.intSequence;";
            }
            System.out.println(sql);
            rs = clsGlobalVarClass.dbMysql.executeResultSet(sql);
            int seq = 1;
            while (rs.next())
            {
                // Object[] ob = {rs.getString(1), rs.getString(2)};
                Object[] ob =
                {
                    seq, rs.getString(2)
                };
                dm1.addRow(ob);
                seq++;
            }
            rs.close();
            tblDesktop.setModel(dm1);
        }
        catch (Exception e)
        {
        }
    }
}
