/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.POSMaster.view;
import com.POSGlobal.controller.clsGlobalVarClass;
import com.POSGlobal.controller.clsUtility;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jai Chandra
 */
public class frmArrangeTransaction extends javax.swing.JFrame {

    private ResultSet rs;
    private DefaultTableModel dmArrageTrans;
    ArrayList<String> arrListTansData = new ArrayList<>();
    private int seqNo;
    clsUtility objUtility = new clsUtility();
    
    public frmArrangeTransaction() {
        initComponents();
        try {
            lblUserCode.setText(clsGlobalVarClass.gUserCode);
            lblPosName.setText(clsGlobalVarClass.gPOSName);
            Timer timer = new Timer(500, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    tickTock();
                }
            });
            timer.setRepeats(true);
            timer.setCoalesce(true);
            timer.setInitialDelay(0);
            timer.start();
            lblFormName.setText(clsGlobalVarClass.gSelectedModule+" Arrange Transaction");

            String sql="select strTransactionName from tbltransbtnsequence "
                + "where strTransactionName='"+cmbType.getSelectedItem()+"'";
            ResultSet rsCount=clsGlobalVarClass.dbMysql.executeResultSet(sql);
            if(rsCount.next())            
            {
                funFillTransButtonGrid(cmbType.getSelectedItem().toString());
            }
            else{
                funLoadTable();
            }            
            rsCount.close();
            
        } catch (Exception e) {
            objUtility.funWriteErrorLog(e);
            e.printStackTrace();
        }
    }
    
    
    private void funSaveRecords()
    {
        try
        {
            String sql;
            sql="delete from tbltransbtnsequence where strTransactionName='"+cmbType.getSelectedItem()+"'";
            clsGlobalVarClass.dbMysql.execute(sql);
            String transName=cmbType.getSelectedItem().toString();
            Map<String,String> hmTransSeq=new HashMap<String,String>();
            
            int cnt1=0;
            for(int cnt=0;cnt<tblArrangeTrans.getRowCount();cnt++)
            {                
                hmTransSeq.put(tblArrangeTrans.getValueAt(cnt1,1).toString(),tblArrangeTrans.getValueAt(cnt1,0).toString());
                cnt1++;
            }
            
            String sqlInsert1="insert into tbltransbtnsequence( ";
            String sqlInsert2="values( ";
            
            for(Map.Entry entry:hmTransSeq.entrySet())
            {
                sqlInsert1+=entry.getKey()+",";
                sqlInsert2+=entry.getValue()+",";
            }
            sqlInsert1+="strTransactionName,strClientCode,strDataPostFlag)";
            sqlInsert2+="'"+transName+"','"+clsGlobalVarClass.gClientCode+"','N')";
            
            //System.out.println(sqlInsert1+sqlInsert2);
            clsGlobalVarClass.dbMysql.execute(sqlInsert1+sqlInsert2);
            JOptionPane.showMessageDialog(null, "Data Insert Successfully");
            
        } catch (Exception ex) {
            objUtility.funWriteErrorLog(ex);
             ex.printStackTrace();
        }
    }
    
    
    
    /**
     * This method is used to tickTock
     */
    public void tickTock() {
        Date date1 = new Date( );
        String new_str = String.format("%tr", date1 );
        String dateAndTime=clsGlobalVarClass.gPOSDateToDisplay+" "+new_str;
        lblclock.setText(dateAndTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbArrangeTrans = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblPosName = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblUserCode = new javax.swing.JLabel();
        lblclock = new javax.swing.JLabel();
        lblHOSign = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tblArrangeTrans = new javax.swing.JTable();
        lblMoveDown = new javax.swing.JLabel();
        lblMoveUp = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblFormName = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        lblType = new javax.swing.JLabel();

        cmbArrangeTrans.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(69, 164, 238));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblProductName.setText("SPOS - Desktop");
        jPanel1.add(lblProductName);
        jPanel1.add(filler4);
        jPanel1.add(filler5);

        lblPosName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPosName.setForeground(new java.awt.Color(255, 255, 255));
        lblPosName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosName.setMaximumSize(new java.awt.Dimension(321, 30));
        lblPosName.setMinimumSize(new java.awt.Dimension(321, 30));
        lblPosName.setPreferredSize(new java.awt.Dimension(321, 30));
        jPanel1.add(lblPosName);
        jPanel1.add(filler6);

        lblUserCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserCode.setForeground(new java.awt.Color(255, 255, 255));
        lblUserCode.setMaximumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setMinimumSize(new java.awt.Dimension(90, 30));
        lblUserCode.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(lblUserCode);

        lblclock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblclock.setForeground(new java.awt.Color(255, 255, 255));
        lblclock.setMaximumSize(new java.awt.Dimension(192, 30));
        lblclock.setMinimumSize(new java.awt.Dimension(192, 30));
        lblclock.setPreferredSize(new java.awt.Dimension(192, 30));
        jPanel1.add(lblclock);

        lblHOSign.setMaximumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setMinimumSize(new java.awt.Dimension(34, 30));
        lblHOSign.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel1.add(lblHOSign);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 570));
        jPanel3.setOpaque(false);

        tblArrangeTrans.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblArrangeTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sequence No", "Module Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArrangeTrans.setRowHeight(25);
        tblArrangeTrans.getTableHeader().setReorderingAllowed(false);
        tblArrangeTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArrangeTransMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tblArrangeTrans);

        lblMoveDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgMoveDown.png"))); // NOI18N
        lblMoveDown.setToolTipText("Move Down");
        lblMoveDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMoveDownMouseClicked(evt);
            }
        });

        lblMoveUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/POSMaster/images/imgMoveUp.png"))); // NOI18N
        lblMoveUp.setToolTipText("Move Up");
        lblMoveUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMoveUpMouseClicked(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn1.png"))); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.setToolTipText("Close ");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn2.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn1.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setToolTipText("Save Changes");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spos/images/imgCmnBtn2.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblFormName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make KOT", "Direct Biller" }));
        cmbType.setToolTipText("Select POS");
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        lblType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblType.setText("Type:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 69, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(lblMoveUp)
                                .addGap(10, 10, 10)
                                .addComponent(lblMoveDown)))
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(lblFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(lblType)
                    .addContainerGap(724, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoveUp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoveDown, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(549, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblArrangeTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArrangeTransMouseClicked
        // TODO add your handling code here:
        seqNo = 0;
        seqNo = tblArrangeTrans.getSelectedRow();
    }//GEN-LAST:event_tblArrangeTransMouseClicked

    private void lblMoveDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoveDownMouseClicked
        if (tblArrangeTrans.getRowCount() == seqNo + 1) {
            // do Nothing This is last row
        } else {
            String tempSelectedFormName = tblArrangeTrans.getValueAt(seqNo, 1).toString();
            String tempLowerFormName = tblArrangeTrans.getValueAt(seqNo + 1, 1).toString();
            tblArrangeTrans.setValueAt(tempSelectedFormName, seqNo + 1, 1);
            tblArrangeTrans.setValueAt(tempLowerFormName, seqNo, 1);
            seqNo = seqNo + 1;
            tblArrangeTrans.setRowSelectionInterval(seqNo, seqNo);

        }
    }//GEN-LAST:event_lblMoveDownMouseClicked

    private void lblMoveUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoveUpMouseClicked
        // TODO add your handling code here:
        if (seqNo == 0) {
            //Do nothing This is first row
        } else {
            String tempSelectedFormName = tblArrangeTrans.getValueAt(seqNo, 1).toString();
            String tempUpperFormName = tblArrangeTrans.getValueAt(seqNo - 1, 1).toString();
            tblArrangeTrans.setValueAt(tempSelectedFormName, seqNo - 1, 1);
            tblArrangeTrans.setValueAt(tempUpperFormName, seqNo, 1);
            seqNo = seqNo - 1;
            tblArrangeTrans.setRowSelectionInterval(seqNo, seqNo);

        }
    }//GEN-LAST:event_lblMoveUpMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
         clsGlobalVarClass.hmActiveForms.remove("Arrange Transaction");
    }//GEN-LAST:event_btnCloseActionPerformed

     private void funFillTransButtonGrid(String type){
        try
        {
            String sql;
            dmArrageTrans = (DefaultTableModel) tblArrangeTrans.getModel();
            dmArrageTrans.setRowCount(0);
            sql = "select * from tbltransbtnsequence "
                + "where strTransactionName='" + type + "' ";
            ResultSet rsFillGrid = clsGlobalVarClass.dbMysql.executeResultSet(sql);
            TreeMap<Integer, String> hm = new TreeMap<Integer, String>();
            if (rsFillGrid.next())
            {
                hm.put(Integer.parseInt(rsFillGrid.getString(1)), "strPLUButton");
                hm.put(Integer.parseInt(rsFillGrid.getString(2)), "strSettleBillButton");
                hm.put(Integer.parseInt(rsFillGrid.getString(3)), "strDeliveryBoyButton");
                hm.put(Integer.parseInt(rsFillGrid.getString(4)), "strHomeDeliveryButton");
                hm.put(Integer.parseInt(rsFillGrid.getString(5)), "strTakeAwayButton");
                hm.put(Integer.parseInt(rsFillGrid.getString(6)), "strCheckKOTButton");
                hm.put(Integer.parseInt(rsFillGrid.getString(7)), "strModifierButton");
                hm.put(Integer.parseInt(rsFillGrid.getString(8)), "strNCKOTButton");
            }
            
            for (Map.Entry m : hm.entrySet())
            {
                Object[] ob =
                {
                    m.getKey(), m.getValue()
                };
                dmArrageTrans.addRow(ob);
            }
            tblArrangeTrans.setModel(dmArrageTrans);

        }
        catch (Exception ex) {
            objUtility.funWriteErrorLog(ex);
            ex.printStackTrace();
        }
   }
    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
        funFillTransButtonGrid(cmbType.getSelectedItem().toString());
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        // TODO add your handling code here:
        funSaveRecords();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        clsGlobalVarClass.hmActiveForms.remove("Arrange Transaction");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        clsGlobalVarClass.hmActiveForms.remove("Arrange Transaction");
    }//GEN-LAST:event_formWindowClosing

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        clsGlobalVarClass.hmActiveForms.remove("Arrange Transaction");
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmArrangeTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmArrangeTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmArrangeTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmArrangeTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmArrangeTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbArrangeTrans;
    private javax.swing.JComboBox cmbType;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFormName;
    private javax.swing.JLabel lblHOSign;
    private javax.swing.JLabel lblMoveDown;
    private javax.swing.JLabel lblMoveUp;
    private javax.swing.JLabel lblPosName;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUserCode;
    private javax.swing.JLabel lblclock;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblArrangeTrans;
    // End of variables declaration//GEN-END:variables

    
    private void funLoadTable() {
        try {
            dmArrageTrans = (DefaultTableModel) tblArrangeTrans.getModel();
            dmArrageTrans.setRowCount(0);
            arrListTansData.add("strPLUButton");
            arrListTansData.add("strSettleBillButton");
            arrListTansData.add("strDeliveryBoyButton");
            arrListTansData.add("strHomeDeliveryButton");
            arrListTansData.add("strTakeAwayButton");
            arrListTansData.add("strCheckKOTButton");
            arrListTansData.add("strModifierButton");
            arrListTansData.add("strNCKOTButton");
      
            int seq=1;
            for(int a=0;a<=arrListTansData.size();a++){
                Object[] ob = {seq, arrListTansData.get(a)};
                dmArrageTrans.addRow(ob);
                seq++;
            }
            rs.close();
            
            
           tblArrangeTrans.setModel(dmArrageTrans);
         
        } catch (Exception e) {
            objUtility.funWriteErrorLog(e);
        }
    }
}

